In [53]:
#Multi-Layer Perceptron using Low level API from TensorFlow
from sklearn import datasets
import tensorflow as tf
import numpy as np

In [87]:
#https://archive.ics.uci.edu/ml/datasets/Iris
iris = datasets.load_iris()
#Attributes
#1. sepal length in cm
#2. sepal width in cm
#3. petal length in cm
#4. petal width in cm

#Class:
#-- Iris Setosa
#-- Iris Versicolour
#-- Iris Virginica

In [55]:
X = iris.data

In [56]:
y = iris.target

In [57]:
#Padronização: 
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [59]:
#One hot encoding: adjust the data format to network exit layer format: 3 columns equal to 3 exit neurons equals to 3 classes!
"""
[0]         [1][0][0]       Setosa
[1]    to   [0][1][0]       Versicolour
[2]         [0][0][1]       Virginica

"""
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categorical_features = [0])
#just lines: array format
y.shape

(150,)

In [60]:
y = y.reshape(-1, 1)

#lines and columns: matrix format: ok!
y.shape

(150, 1)

In [61]:
y = onehot.fit_transform(y).toarray()
y

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [62]:
#Partition to trainning and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [63]:
#70% for trainning: 105 elements
X_train.shape

(105, 4)

In [64]:
#30% for test: 45 elements
X_test.shape

(45, 4)

In [65]:
#Mounting the NEURAL NETWORK ARCHITECTURE: input layer
neurons_input_layer = X.shape[1] #
neurons_input_layer

4

In [66]:
#Mounting the NEURAL NETWORK ARCHITECTURE: hidden layer
#Formula to discover the number of neurons in hidden layer: (number of atts PLUS number of classes) DIVIDED BY 2
#np.ceil round a floating number to down
neurons_hidden_layer = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neurons_hidden_layer

4

In [67]:
#Mounting the NEURAL NETWORK ARCHITECTURE: exit layer
neurons_exit_layer = y.shape[1]
neurons_exit_layer

3

In [68]:
#Matrix of Weights
W = {'hidden': tf.Variable(tf.random_normal([neurons_input_layer, neurons_hidden_layer])),
     'exit': tf.Variable(tf.random_normal([neurons_hidden_layer, neurons_exit_layer]))}

In [69]:
#Array of Biases
b = {'hidden': tf.Variable(tf.random_normal([neurons_hidden_layer])),
     'exit': tf.Variable(tf.random_normal([neurons_exit_layer]))}

In [70]:
#Using placeholders: 

#None: It dont specificate the number of elements (objects),
#neurons_input_layer: number of features(columns, attributes)
xph = tf.placeholder('float', [None, neurons_input_layer])

#neurons_exit_layer: number of classes(i.e. 3): Setosa, Versicolour and Virginica
yph = tf.placeholder('float', [None, neurons_exit_layer])

In [71]:
#Multi-Layer Perceptron!
def mlp(X, W, bias):
    #Mounting the tensorflow (graph of tensors)
    #According to: ((X . W) + bias)
    hidden_layer = tf.add( tf.matmul( X, W['hidden']), bias['hidden'] )
    
    #Using relu activation function
    hidden_layer_activation = tf.nn.relu(hidden_layer)
    #Exit layer receives the output of hidden layer as its input and calculate the summation (as function above)
    exit_layer = tf.add( tf.matmul( hidden_layer_activation, W['exit']), bias['exit'] )
    return exit_layer

In [73]:
model = mlp(xph, W, b)

In [75]:
#It is not necessary use softmax, cause the method below already do it!
error = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = model, labels = yph))
#Adam
optimizer = tf.train.AdamOptimizer(learning_rate = 0.0001).minimize(error)

In [82]:
#Mini-batch trainning
batch_size = 8

#13 batches with 9 elements in each
number_of_batches = int(len(X_train) / batch_size)
number_of_batches

13

In [78]:
#X_batches has all the 13 batches
X_batches = np.array_split(X_train, total_batches)
X_batches
#9 elements in each batch

[array([[-1.02184904,  0.55861082, -1.34022653, -1.3154443 ],
        [ 0.55333328, -1.28296331,  0.70592084,  0.92230284],
        [-1.26418478,  0.78880759, -1.05603939, -1.3154443 ],
        [-0.90068117, -1.28296331, -0.4308277 , -0.13075464],
        [ 1.64384411,  0.32841405,  1.27429511,  0.79067065],
        [ 0.55333328,  0.55861082,  0.53540856,  0.52740629],
        [-1.14301691, -1.28296331,  0.42173371,  0.65903847],
        [ 0.67450115, -0.59237301,  1.0469454 ,  1.18556721],
        [-0.90068117,  0.78880759, -1.2833891 , -1.3154443 ]]),
 array([[-0.29484182, -0.36217625, -0.08980313,  0.13250973],
        [-1.26418478,  0.09821729, -1.22655167, -1.3154443 ],
        [ 0.55333328,  0.55861082,  1.27429511,  1.71209594],
        [-1.02184904,  0.32841405, -1.45390138, -1.3154443 ],
        [-0.41600969, -1.74335684,  0.13754657,  0.13250973],
        [ 0.55333328, -0.36217625,  1.0469454 ,  0.79067065],
        [ 0.67450115,  0.32841405,  0.42173371,  0.3957741 ],
      

In [79]:
#the first position of batch
X_batches[0]

array([[-1.02184904,  0.55861082, -1.34022653, -1.3154443 ],
       [ 0.55333328, -1.28296331,  0.70592084,  0.92230284],
       [-1.26418478,  0.78880759, -1.05603939, -1.3154443 ],
       [-0.90068117, -1.28296331, -0.4308277 , -0.13075464],
       [ 1.64384411,  0.32841405,  1.27429511,  0.79067065],
       [ 0.55333328,  0.55861082,  0.53540856,  0.52740629],
       [-1.14301691, -1.28296331,  0.42173371,  0.65903847],
       [ 0.67450115, -0.59237301,  1.0469454 ,  1.18556721],
       [-0.90068117,  0.78880759, -1.2833891 , -1.3154443 ]])

In [84]:
#TRAINNING -----------------------------------------------------------------------------------
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # 3000 epochs
    for epoch in range(3000):
        mean_error = 0.0
        
        # 13
        number_of_batches = int(len(X_train) / batch_size)
        
        #batches for X_train data: 13 batches, 9 elements in each batch
        X_batches = np.array_split(X_train, number_of_batches)
        
        #Batches for Y_train label: batchs with the labels (correct answers): 13 batches, 9 elements in each batch
        y_batches = np.array_split(y_train, number_of_batches)
        
        for i in range(number_of_batches):
            
            #take the actual batch (x and y...i.e...data and label)
            #X_batch: batch in position i containing data
            #y_batch: batch in position i containing labels
            X_batch_i, y_batch_i = X_batches[i], y_batches[i]
            
            #train for all the elements of each batch_i
            _, cost = sess.run([optimizer, error], feed_dict = {xph: X_batch_i, yph: y_batch_i})
            #after train with ALL the batch elements in position i:
            
            #calculate the error! IS THIS WRONG....SHOULD BE COST/ 9 (batch size)
            mean_error += cost / number_of_batches
        
        #show the error in each 500 epochs
        if epoch % 500 == 0:
            print('Epoch: ' + str((epoch + 1)) + ' error: ' + str(mean_error))
    
    #get the last values of weights W and biases b
    final_W, final_b = sess.run([W, b])

Epoch: 1 error: 1.6441119404939504
Epoch: 501 error: 0.2633375898003578
Epoch: 1001 error: 0.16166647208424714
Epoch: 1501 error: 0.11563897175857654
Epoch: 2001 error: 0.09539411704127604
Epoch: 2501 error: 0.08516037209819143


In [85]:
final_W

{'hidden': array([[-1.4155977 , -0.2754175 , -0.07687059,  0.3593265 ],
        [ 0.10859597, -1.0605419 , -0.7184432 , -1.7719336 ],
        [-0.7827799 , -0.56404203,  1.5312911 ,  2.9205263 ],
        [-0.2868071 , -0.46534896,  2.2740886 ,  0.0133655 ]],
       dtype=float32), 'exit': array([[ 1.6104941 , -2.7058127 , -1.0018333 ],
        [-1.1403052 ,  0.74832904, -0.29976586],
        [-2.7739315 , -0.6942593 ,  1.9633021 ],
        [-2.6071482 ,  0.19647443,  0.22588797]], dtype=float32)}

In [86]:
final_b

{'hidden': array([-0.08844309,  0.61769325, -1.051485  ,  1.5916853 ], dtype=float32),
 'exit': array([ 1.1486399,  1.4482061, -2.3456347], dtype=float32)}

In [90]:
#TEST --------------------------------------------------------------------------------
test_predict = mlp(xph, final_W, final_b)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    #without softmax
    r1 = sess.run(test_predict, feed_dict = {xph: X_test})
    
    #with softmax
    r2 = sess.run(tf.nn.softmax(r1))
    
    #transforming the format to y_test format
    #argmax returns a index of maximum in a axis
    #i.e.Returns the index with the largest value across axes of a tensor. 
    r3 = sess.run(tf.argmax(r2, 1))

In [91]:
#without softmax
r1

array([[-17.939953  ,   0.5074645 ,   3.8464396 ],
       [  4.220045  ,  -5.058414  ,  -5.4199014 ],
       [-23.144184  ,  -0.3982674 ,   6.85491   ],
       [  4.455036  ,  -6.503121  ,  -6.4735327 ],
       [-10.682699  ,   3.0089312 ,  -1.4424052 ],
       [ -8.732039  ,   1.9162519 ,  -0.60153687],
       [-14.296958  ,   1.73534   ,  -3.5832307 ],
       [-15.069809  ,   0.8601033 ,   2.5125806 ],
       [-24.798298  ,   1.1207875 ,   5.240491  ],
       [-10.731112  ,   2.0244565 ,  -0.25167632],
       [-18.951801  ,   0.33912802,   4.4006395 ],
       [ -5.3801365 ,   2.060804  ,  -2.1533384 ],
       [-22.629688  ,  -0.3689636 ,   6.5985823 ],
       [-12.619935  ,   2.8489118 ,  -1.4035116 ],
       [-39.047127  ,  -0.5462115 ,  10.718975  ],
       [-21.094435  ,  -0.5348939 ,   6.5613804 ],
       [-24.020363  ,   0.19543731,   5.842429  ],
       [  4.5307407 ,  -4.234107  ,  -4.449524  ],
       [  4.1044884 ,  -5.1508274 ,  -5.5957003 ],
       [-16.416544  ,   4.56235

In [92]:
#with softmax
r2   

array([[3.33542471e-10, 3.42580564e-02, 9.65741932e-01],
       [9.99841452e-01, 9.34001000e-05, 6.50662550e-05],
       [9.35947961e-14, 7.07420870e-04, 9.99292612e-01],
       [9.99964714e-01, 1.74147699e-05, 1.79377312e-05],
       [1.11883014e-06, 9.88470435e-01, 1.15285013e-02],
       [2.19692920e-05, 9.25359190e-01, 7.46188462e-02],
       [1.08427393e-07, 9.95124042e-01, 4.87586111e-03],
       [1.94063468e-08, 1.60774410e-01, 8.39225531e-01],
       [8.85767899e-14, 1.59895159e-02, 9.84010518e-01],
       [2.61743889e-06, 9.06878591e-01, 9.31187719e-02],
       [7.09166198e-11, 1.69313587e-02, 9.83068585e-01],
       [5.77850558e-04, 9.84860897e-01, 1.45611661e-02],
       [2.02261900e-13, 9.41075152e-04, 9.99058902e-01],
       [1.88724627e-07, 9.85969782e-01, 1.40300635e-02],
       [2.43697486e-22, 1.28110933e-05, 9.99987245e-01],
       [9.74703608e-13, 8.27499374e-04, 9.99172509e-01],
       [1.06960705e-13, 3.51571059e-03, 9.96484280e-01],
       [9.99718010e-01, 1.56081

In [93]:
r3

array([2, 0, 2, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 0, 0,
       0, 1, 2, 2, 1, 2, 1, 1, 2, 0, 1, 0, 2, 1, 0, 2, 2, 2, 0, 0, 0, 0,
       2], dtype=int64)

In [95]:
y_test2 = np.argmax(y_test, 1)
y_test2

array([2, 0, 2, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 0, 0,
       0, 1, 2, 2, 1, 2, 1, 1, 2, 0, 1, 0, 2, 1, 0, 2, 2, 2, 0, 0, 0, 0,
       2], dtype=int64)

In [96]:
#comparing both arrays: computing the accuracy: 100%
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, r3)
accuracy

1.0