In [3]:
import tensorflow as tf

In [5]:
a = tf.constant(([2,3],[-2,3]))

In [7]:
b = tf.constant(([1,2],[5,-6]))

In [10]:
mult = tf.matmul(a,b) #TF.MATMUL: TEM QUE USAR ESSE PRA NÃO MULTIPLICAR ERRADO!! AB != BA

In [11]:
with tf.Session() as ses:
    print(ses.run(a))
    print("\n   *\n")
    print(ses.run(b))
    print("\n    =\n")
    print(ses.run(mult))

[[ 2  3]
 [-2  3]]

   *

[[ 1  2]
 [ 5 -6]]

    =

[[ 17 -14]
 [ 13 -22]]


In [12]:
c = tf.constant(([2,2],[3,3],[-2,0])) # Matrix C(3,2) D(2,3)

In [13]:
d = tf.constant(([3,3,1],[4,5,2]))

In [14]:
multCD = tf.matmul(c,d)

In [15]:
with tf.Session() as ses:
    print(ses.run(multCD))

[[14 16  6]
 [21 24  9]
 [-6 -6 -2]]
