In [98]:
import tensorflow as tf
import numpy as np

In [99]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [100]:
y = np.array([[0.0], [1.0], [1.0], [1.0]])
y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [101]:
W = tf.Variable(tf.zeros([2,1], dtype = tf.float64) )
type(W)

tensorflow.python.ops.variables.RefVariable

In [102]:
def step_function(x):
    return  tf.cast(tf.to_float(tf.math.greater_equal(x,1)), tf.float64)

In [103]:
init = tf.global_variables_initializer()

In [104]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(W))


[[0.]
 [0.]]


In [105]:
#multiplicate the inputs (two inputs each) with the respective weights 
exit_layer = tf.matmul(X, W)
exit_layer

<tf.Tensor 'MatMul_8:0' shape=(4, 1) dtype=float64>

In [106]:
with tf.Session() as sess:
    sess.run(init)
    print("summation before step function\n", sess.run(exit_layer))
    #print(sess.run(step_function(0)))

summation before step function
 [[0.]
 [0.]
 [0.]
 [0.]]


In [107]:
exit_layer_activation = step_function(exit_layer)
exit_layer_activation

<tf.Tensor 'Cast_11:0' shape=(4, 1) dtype=float64>

In [108]:
with tf.Session() as sess:
    sess.run(init)
    print("step_function:\n",sess.run(exit_layer_activation))

step_function:
 [[0.]
 [0.]
 [0.]
 [0.]]


In [109]:
error = tf.subtract(y, exit_layer_activation)

In [110]:
with tf.Session() as sess:
    sess.run(init)
    print("error:\n",sess.run(error))

error:
 [[0.]
 [1.]
 [1.]
 [1.]]


In [111]:
delta = tf.matmul(X, error, transpose_a = True)
delta

<tf.Tensor 'MatMul_9:0' shape=(2, 1) dtype=float64>

In [112]:
learning_rate = 0.1

In [113]:
#assign assign to W the new weight.
trainning = tf.assign(W, tf.add (W, tf.multiply(delta, learning_rate)))


In [114]:
with tf.Session() as sess:
    sess.run(init)
    print(X, "\n")
    print(sess.run(tf.transpose(X)), "\n")
    print(sess.run(trainning))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]] 

[[0. 0. 1. 1.]
 [0. 1. 0. 1.]] 

[[0.2]
 [0.2]]


In [115]:
with tf.Session() as sess:
    sess.run(init)
    epoch = 0

    for i in range(15):
        epoch += 1
        # _ because trainning var returns NOTHING, just assign!
        total_error, _ = sess.run([error, trainning])
        error_summation = tf.reduce_sum(total_error)
        print(total_error)
        print("Epoch: ", epoch, "Error: ", sess.run(error_summation))
        if(error_summation.eval() == 0):
            break
        final_W = sess.run(W)
        

[[0.]
 [1.]
 [1.]
 [1.]]
Epoch:  1 Error:  3.0
[[0.]
 [1.]
 [1.]
 [1.]]
Epoch:  2 Error:  3.0
[[0.]
 [1.]
 [1.]
 [1.]]
Epoch:  3 Error:  3.0
[[0.]
 [1.]
 [1.]
 [0.]]
Epoch:  4 Error:  2.0
[[0.]
 [1.]
 [1.]
 [0.]]
Epoch:  5 Error:  2.0
[[0.]
 [1.]
 [1.]
 [0.]]
Epoch:  6 Error:  2.0
[[0.]
 [1.]
 [1.]
 [0.]]
Epoch:  7 Error:  2.0
[[0.]
 [0.]
 [0.]
 [0.]]
Epoch:  8 Error:  0.0


In [116]:
final_W

array([[1.],
       [1.]])

In [117]:
exit_layer_test = tf.matmul(X, final_W)
exit_layer_activation_test = step_function(exit_layer_test)

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(exit_layer_activation_test))

[[0.]
 [1.]
 [1.]
 [1.]]
