In [ ]:
import tensorflow as tf

In [14]:
placeH = tf.placeholder('float', None) #None is the size of placeholder

In [17]:
operation = placeH + 2 #just a graph. The operation doesn't happened yet

In [19]:
with tf.Session() as ses:
    result = ses.run(operation, feed_dict = {placeH: [1,2,3]})
    print(result)

[3. 4. 5.]


In [21]:
placeH2 = tf.placeholder('float', [None, 5])# e.g.: N rows, 5 columns
operation2 = placeH2 + 5

In [23]:
with tf.Session() as ses:
    data = [[1,2,3,4,5,],[6,7,8,9,10]]
    result2 = ses.run(operation2, feed_dict = {placeH2: data})
    print(result2)

[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
