In [15]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [16]:
base.shape

(21613, 21)

In [17]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [18]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [19]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [20]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [21]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [22]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [23]:
import tensorflow as tf

In [24]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [25]:
colunas

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [26]:
#Lets use estimators..from Tensorflow high leve API
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

W1104 09:26:38.301990  7140 estimator.py:1811] Using temporary folder as model directory: C:\Users\ALLANS~1\AppData\Local\Temp\tmpovwydjjx


In [27]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [28]:
X_treinamento.shape

(15129, 1)

In [29]:
y_treinamento.shape

(15129, 1)

In [30]:
X_teste.shape

(6484, 1)

In [ ]:
y_teste.shape

(6484, 1)

In [ ]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': X_treinamento}, y_treinamento,
                                                        batch_size = 32, num_epochs = None, 
                                                        shuffle = True)

In [ ]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': X_teste}, y_teste, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [ ]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

W1104 09:26:40.619955  7140 deprecation.py:323] From C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W1104 09:26:40.653935  7140 deprecation.py:323] From C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1104 09:26:40.659934  7140 deprecation.py:323] From C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_func

In [ ]:
#THE ALGOTIHTM EXECUTES 10K TIMES 1000 EPOCHS
#WHAT THE DIFFERENCE BETWEEN EPOCHS AND STEPS...GRADIENT DESCENT
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

W1104 09:26:59.055398  7140 deprecation.py:323] From C:\Users\Allan Santos\.conda\envs\AM\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


In [ ]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

In [ ]:
metricas_treinamento

In [ ]:
metricas_teste

In [ ]:
#INFERÊNCIA DE NOVOS VALORES
import numpy as np
novas_casas = np.array([[800], [900], [1000], [2500], [3000], [1500]])
novas_casas

In [ ]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

In [ ]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [ ]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [ ]:
previsoes

In [ ]:
list(previsoes)

In [ ]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))