In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(([1,2,3]), name="a")
b = tf.constant(([4,5,6]),name="b")

In [4]:
type(a)

tensorflow.python.framework.ops.Tensor

In [5]:
print(a) #IT'S  VECTOR

Tensor("a:0", shape=(3,), dtype=int32)


In [6]:
sum = a + b

In [12]:
with tf.Session() as ses:
    print(ses.run(sum))
    

[5 7 9]


In [13]:
matrix_a = tf.constant(([2,3,4,], [8,7,6]), name="matrix_1")

In [14]:
matrix_b = tf.constant(([5,6,7],[3,4,5]), name="matrix_2" )

In [18]:
matrix_sum = tf.add(matrix_a, matrix_b)

In [25]:
with tf.Session() as ses:
    print(ses.run(matrix_a))
    print('\n   +\n')
    print(ses.run(matrix_b))
    print('\n   =\n')
    print(ses.run(matrix_sum))

[[2 3 4]
 [8 7 6]]

   +

[[5 6 7]
 [3 4 5]]

   =

[[ 7  9 11]
 [11 11 11]]


In [35]:
matrix_c = tf.constant(([1,2,3],[4,5,6]))
matrix_d = tf.constant(([1],[2]))
sum_2 = tf.add(matrix_c, matrix_d) #somou todos elementos da linha i(j1,j2,j3) da matriz c com o (i1,j1) de d
#da mesma forma, para toda a linha i2 (j1,j2,j3) com j2 da matriz d

In [36]:
with tf.Session() as ses:
    print(ses.run(matrix_c))
    print("\n   +\n")
    print(ses.run(matrix_d))
    print("\n   =\n")
    print(ses.run(sum_2)) 

[[1 2 3]
 [4 5 6]]

   +

[[1]
 [2]]

   =

[[2 3 4]
 [6 7 8]]
