In [ ]:
"""
https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling2D
"""

In [2]:
import tensorflow as tf

# #1

In [9]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])

In [12]:
x = tf.reshape(x, [1, 3, 3, 1])
x

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)>

In [5]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   strides=(1, 1), padding='valid')
max_pool_2d(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[5.],
         [6.]],

        [[8.],
         [9.]]]], dtype=float32)>

# #2

In [15]:
x = tf.constant([[1., 2., 3., 4.],
                 [5., 6., 7., 8.],
                 [9., 10., 11., 12.]])
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)>

In [16]:
x = tf.reshape(x, [1, 3, 4, 1])
x

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]]], dtype=float32)>

### padding='valid'

In [18]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   strides=(2, 2), padding='valid') #VALID means "no padding"
max_pool_2d(x)

<tf.Tensor: shape=(1, 1, 2, 1), dtype=float32, numpy=
array([[[[6.],
         [8.]]]], dtype=float32)>

### padding='same'

In [ ]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   strides=(2, 2), padding='same') #SAME
max_pool_2d(x)

# #3: Usage example

In [19]:
input_image = tf.constant([[[[1.], [1.], [2.], [4.]],
                           [[2.], [2.], [3.], [2.]],
                           [[4.], [1.], [1.], [1.]],
                           [[2.], [2.], [1.], [4.]]]])
input_image

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [2.],
         [4.]],

        [[2.],
         [2.],
         [3.],
         [2.]],

        [[4.],
         [1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [1.],
         [4.]]]], dtype=float32)>

In [20]:
output = tf.constant([[[[1], [0]],
                      [[0], [1]]]])
output

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [0]],

        [[0],
         [1]]]])>

In [24]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
   input_shape=(4, 4, 1)))
model.compile('adam', 'mean_squared_error')
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 max_pooling2d_6 (MaxPooling  (None, 2, 2, 1)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.predict(input_image, steps=1)

1/1 [==============================] - 0s 33ms/step


array([[[[2.],
         [4.]],

        [[4.],
         [4.]]]], dtype=float32)